### ISSUE TITLE
Test code snippets in CI

### ISSUE THREAD

**Issue by mitschabaude** [o1-labs/docs2#187]
We should make sure that code snippets can't go out of date with the published version of snarkyjs / zkapp-cli!

**Proposal**

Every code snippet has to be included in a script that can be successfully executed. That script would also live in the docs repo, e.g. one script per docs section.

In the case of tutorials, this also comes pretty natural - there is code for the tutorials anyway (and this would force us to keep that code up to date)

This formulation would give us a lot of flexibility in how we write the snippets. It should be easy to check, we'd just take each individual code snippet line and check if it's one of the lines in some specified file.

**Comment by rjdellecese** [comment]
I had a similar idea for a strategy for testing the code snippets; I'd like your thoughts on it @mitschabaude! I had particularly in mind the tutorials, so I'll use those as the example, but I think it could probably be generalized to apply to any documentation page.

The idea is to simulate a user's experience working through any of the tutorials by writing a script which performs the following steps, once for each tutorial:

1. Extract each code block in the markdown page.
2. In the context of a GitHub Actions job, iterate through each extracted code block sequentially.
    a. If the the code block is labeled `sh` or `bash`, execute it as a shell command.
    b. If the code block is labeled `ts` (or `tsx` or `html` or `css` or `json` or whatever), write the contents of the code block to the file to which it refers, replacing each line that is specified.
3. Ensure throughout this process that all shell commands that are executed have exit codes of zero.
4. That's it!

A few notes:

- Tutorials would need to be rewritten so that each non-shell code block includes easily parseable indications of which file it applies to, but that should be pretty trivial.
- Tutorials 5, 8, and the Anonymous Message Board Example would need a bit more treatment (the addition of line numbers to each code block, also).
- Each job could specify its own starting state (by, for example, `npm install`ing `zkapp-cli` etc.), outside of the context of the documentation page. For the first tutorial, for example, it makes sense to have an **Installation** section where `npm install -g zkapp-cli` happens, just like how in the second, it makes sense not to!
- We could derive the finished example from this process, save it as a build artifact, and publish it somewhere automatically, rather than manually maintaining [a repo of finished tutorial apps](https://github.com/es92/zkApp-examples) (which is error prone). That's kinda cool!
- Like I said, I think this could be adapted nicely to work with any documentation page, but I'd have to think a little bit more about how best to do so.

**Comment by mitschabaude** [comment]
@rjdellecese sorry for the late response. Your ideas are very interesting and definitely worth giving a shot. However, they are also more ambitious than my proposal.

I would suggest that we move forward with an in-between approach: On the tutorials, I encourage you to try out your idea. The examples code snippets, on the other hand, should just use the single-file approach that I proposed. They aren't designed to list you all the shell commands you need to run (that would be good for a tutorial-like flow, but other parts of the docs should obviously skip over steps like setting up a repo and installing dependencies.) Instead, the code snippets are, for the most part, well-served by a very standardized way of executing a particular JS file with node, with particular pre-defined dependencies. (Possible counter-example: Code snippets for integrating into a Web UI, and Jest tests, which could both need a specialized way of running them.) Also, the single-file approach makes it easier to write incomplete code without needing to specify the line numbers that should be replaced.

Independently, I think it's important to move the tutorial code into the docs repo, regardless of how we end up testing it -- we want everything in one place, otherwise keeping it up to date is a pain. I'm just saying this so that you don't have to worry about how to pull in source code from other git repos.

**Comment by rjdellecese** [comment]
All good! I _think_ your concerns with testing non-tutorial docs in this way can be addressed without too much difficulty. I'll outline my thoughts on that below, but in the meantime I'll proceed with work on just the tutorials, and perhaps we can evaluate further whether my other ideas for testing the non-tutorial docs make sense once this approach has been implemented and tested more (on the tutorials)?

### Amended approach for supporting non-tutorial doc testing

#### Concern 1

> They aren't designed to list you all the shell commands you need to run (that would be good for a tutorial-like flow, but other parts of the docs should skip over steps like setting up a repo and installing dependencies.) Instead, the code snippets are, for the most part, well-served by a very standardized way of executing a particular JS file with node, with particular pre-defined dependencies.

I think we can handle the setup steps by placing them outside of the rendered Markdown but executing them in the test script, per the following note from my previous comment:

> Each job could specify its own starting state (by, for example, `npm install`ing `zkapp-cli` etc.), outside of the context of the documentation page. For the first tutorial, for example, it makes sense to have an Installation section where `npm install -g zkapp-cli` happens, just like how in the second, it makes sense not to!

#### Concern 2

> Also, the single-file approach makes it easier to write incomplete code without needing to specify the line numbers that should be replaced.

I think we can handle this pretty neatly by amending the following snippet from my previous comment (new text in bold):

> 2b. If the code block is labeled `ts` (or `tsx` or `html` or `css` or `json` or whatever), write the contents of the code block to the file to which it refers, replacing each line that is specified. **If the code block does not include line numbers, treat it as a self-contained example and test its execution in isolation, like one would an example in a "doctest".**

(By "doctest" I mean something like the Elixir [doctests](https://elixir-lang.org/getting-started/mix-otp/docs-tests-and-with.html) feature, or the [`elm-verify-examples`](https://github.com/stoeffel/elm-verify-examples) package for Elm.)

Granted, this does require that the code in these docs be "complete" in some sense, but this is how the aforementioned "doctest"ing features work, and I think they've shown that this usually ends up being quite nice.

---

> Independently, I think it's important to move the tutorial code into the docs repo, regardless of how we end up testing it -- we want everything in one place, otherwise keeping it up to date is a pain. I'm just saying this so that you don't have to worry about how to pull in source code from other git repos.

Thank you, that sounds great 👍

**Comment by rjdellecese** [comment]
I see that the tutorials are being moved into this repo here: https://github.com/o1-labs/docs2/pull/203 (per https://github.com/o1-labs/docs2/issues/201, maybe?).

**Comment by mitschabaude** [comment]
@rjdellecese I like your answer to concern 1. However, re concern 2, I don't think we should force us to write complete code comments which are executable in isolation. Especially given that there's a solution (checking inclusion in a prepared file) which doesn't have any downsides IMO

**Comment by mitschabaude** [comment]
> 

Yes! It could make sense for you to work off of that branch. We're moving them to more easily bring them up to date with the next release

**Comment by rjdellecese** [comment]
> I don't think we should force us to write complete code comments which are executable in isolation.

Fair, I could see that being too cumbersome (for us and for the reader).

> Especially given that there's a solution (checking inclusion in a prepared file) which doesn't have any downsides IMO

I think the possible downside is just that the fact some setup step/dependency is not included in the rendered doc, and its absence prevents a reader from understanding or being able to reproduce the sample code (because it's hidden in the testing script).

**Comment by rjdellecese** [comment]
FYI, I'll be unavailable starting tomorrow until the 27th or 28th. Once I'm back, my plan is to finish and put up a proof-of-concept PR applying the discussed strategy to only the first tutorial!

**Comment by rjdellecese** [comment]
Actually, I did it today. https://github.com/o1-labs/docs2/pull/209

**Comment by jasongitmail** [comment]
Closing as done via https://github.com/o1-labs/docs2/pull/209/
