### ISSUE TITLE
Site search doesn't include content from SnarkyJS API reference

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/docs2#256]
<img width="1151" alt="docs" src="https://user-images.githubusercontent.com/50032291/215773114-1818f0d3-0a27-4f1c-9756-79b1aa7785f4.png">

Caused by the SnarkyJS API reference being auto-generated?

**Comment by carterbrett** [comment]
I'm not sure how broad the issue is, but search also appears to not cover tutorials. Also auto-generated content maybe?

**Comment by jasongitmail** [comment]
Thanks for the extra details. We'll need to confirm search index is being rebuilt automatically--something may have broke there

**Comment by MartinMinkov** [comment]
This likely happens when the [snarkyjs-api-reference job](https://github.com/o1-labs/docs2/blob/main/.github/workflows/snarkyjs-api-reference.yml) is run manually, resulting in the search index job not running properly. We should add logic to the `snarkyjs-api-reference` job to run the [algolia-search job](https://github.com/o1-labs/docs2/blob/main/.github/workflows/algolia-search.yml) after as well.

**Comment by nicc** [comment]
Indirectly Irresponsible Individual: @ymekuria
