### ISSUE TITLE
HF audit zkApp docs: o1js FAQ /zkapps/faq.mdx 

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#460]
Audit and update all zkApp docs for technical accuracy prior to hard fork #459
Before the HF, verify technical content in 
o1js FAQ 
- should this topic be renamed to zkApps FAQ? 
- do we need another topic? 

https://docs.minaprotocol.com/zkapps/faq
https://github.com/o1-labs/docs2/blob/main/docs/zkapps/faq.mdx

53 lines, need more FAQs, related to https://app.zenhub.com/workspaces/zkapps-product-eng-6130fedb3b0fc600123d8796/issues/gh/o1-labs/docs2/338

**Comment by barriebyron** [comment]
@MartinMinkov Did I hear correctly that you scraped common FAQs from Discord? Can we leverage those questions? 
I am all eyes and ears... please teach me

**Comment by MartinMinkov** [comment]
The scrape was done manually since I do not have the authorization to deploy a discord bot into the MF channels 😭

If we wanted to add more Q&As from our discord, we either need to spend some time manually going through them and picking ones we like, or have a bot go through and record everything and we can apply some filtering.

**Comment by barriebyron** [comment]
@MartinMinkov  I remember some Slack convo activity about you getting access permissions to add the Discord bot, has that access been granted?

**Comment by barriebyron** [comment]
first iteration https://github.com/o1-labs/docs2/pull/667
