### ISSUE TITLE
ZkProgram doc updates for new non-experimental 

### ISSUE THREAD

**Issue by barriebyron** [o1-labs/docs2#711]
We missed corresponding doc updates for https://github.com/o1-labs/o1js/pull/1200 
@garwalsh  can you provide product guidance on how we present the ZkProgram API. 
It will be helpful to have a doc we can link to. The only doc that mentions it is https://docs.minaprotocol.com/zkapps/o1js/recursion with an experimental flag. 

Questions: 
how to use which flavor? 
benefits and differences?

**Comment by garwalsh** [comment]
@mitschabaude 
In https://github.com/o1-labs/o1js/pull/1200 it states:
- name is required in the new non-experimental API, but still optional in the old Experimental.ZkProgram

When you say "the old Experimental.ZkProgram" does that refer to a developer who has not updated to today's release?
I ask because I don't think we need to keep docs that align with deprecated versions of o1js.

If that's the case, then outstanding docs work should be:
- https://docs.minaprotocol.com/zkapps/o1js/recursion
-- Remove experimental callout
-- Remove experiemntal in code snippets
-- Add name argument in code snippets

- https://docs.minaprotocol.com/zkapps/tutorials/recursion
-- Remove experimental in code snippets
-- Add name argument in code snippets

**Comment by mitschabaude** [comment]
Yes agree with that assessment @garwalsh
